### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by Wangmmstar** [milmillin/passive-gripper#3]
cmake --build -j .   when I run this line, it shows no this instruction. So I changed to cmake --build .      But it keeps giving me an error:
when 100%:
 /end-effector/passive-gripper/src-batch/main.cpp:7:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/psg-batch.dir/build.make:107: recipe for target 'CMakeFiles/psg-batch.dir/src-batch/main.cpp.o' failed
make[2]: *** [CMakeFiles/psg-batch.dir/src-batch/main.cpp.o] Error 1
CMakeFiles/Makefile2:557: recipe for target 'CMakeFiles/psg-batch.dir/all' failed
make[1]: *** [CMakeFiles/psg-batch.dir/all] Error 2
Makefile:170: recipe for target 'all' failed
make: *** [all] Error 2

Could you provide any suggestions to solve it?  Thanks very much!!

**Comment by Wangmmstar** [comment]
Update: It's because of my gcc version is below than 9. 
I changed the src-batch/main.cpp. In line 7, change to #include <experimental/filesystem>.  In Line 24, change to namespace fs = std::experimental::filesystem; 
It worked!

**Comment by milmillin** [comment]
Thanks for the fixes.
