### ISSUE TITLE
Size error

### ISSUE THREAD

**Issue by Wangmmstar** [milmillin/passive-gripper#4]
Hello, no matter what stl file I imported, whether the millimeter check box checked or not, it keeps giving me the error:

GtkDialog mapped without a transient parent. This is discouraged.
passive-gripper: passive-gripper/external/libigl/external/eigen/Eigen/src/Core/PlainObjectBase.h:285: void Eigen::PlainObjectBase<Derived>::resize(Eigen::Index, Eigen::Index) [with Derived = Eigen::Matrix<double, 3, 1>; Eigen::Index = long int]: Assertion `(!(RowsAtCompileTime!=Dynamic) || (rows==RowsAtCompileTime)) && (!(ColsAtCompileTime!=Dynamic) || (cols==ColsAtCompileTime)) && (!(RowsAtCompileTime==Dynamic && MaxRowsAtCompileTime!=Dynamic) || (rows<=MaxRowsAtCompileTime)) && (!(ColsAtCompileTime==Dynamic && MaxColsAtCompileTime!=Dynamic) || (cols<=MaxColsAtCompileTime)) && rows>=0 && cols>=0 && "Invalid sizes when resizing a matrix or array."' failed.
Aborted (core dumped)

DO you have any idea or suggestions?  Thank you very much

**Comment by milmillin** [comment]
Did you resolve this issue?

**Comment by Wangmmstar** [comment]
> Did you resolve this issue?

Thanks for your reply. I used the topy in your repository, this error was fixed!

**Comment by Wangmmstar** [comment]
> Did you resolve this issue?

I imported the example stl file provided in your repository, like the C8.stl, it worked without error. However, I downloaded a stl online, it still throw the same error. The stl file I tried to import is attached below. 
[STl.zip](https://github.com/milmillin/passive-gripper/files/11123464/STl.zip)
