### ISSUE TITLE
bin file

### ISSUE THREAD

**Issue by Wangmmstar** [milmillin/passive-gripper#6]
After topology optimization, a .bin file should be generated. Staying on the "Topo Opt" tool, click on "Load Result Bin" and browse to the .bin file.  AFter I run the topy, just generate vtk file while no .bin file. I manually convert vtk to bin, but it keeps give me error!!!

GtkDialog mapped without a transient parent. This is discouraged.
passive-gripper: /mnt/study/mengjun/end-effector/passive-gripper/external/libigl/external/eigen/Eigen/src/Core/PlainObjectBase.h:285: void Eigen::PlainObjectBase<Derived>::resize(Eigen::Index, Eigen::Index) [with Derived = Eigen::Matrix<double, -1, 1>; Eigen::Index = long int]: Assertion `(!(RowsAtCompileTime!=Dynamic) || (rows==RowsAtCompileTime)) && (!(ColsAtCompileTime!=Dynamic) || (cols==ColsAtCompileTime)) && (!(RowsAtCompileTime==Dynamic && MaxRowsAtCompileTime!=Dynamic) || (rows<=MaxRowsAtCompileTime)) && (!(ColsAtCompileTime==Dynamic && MaxColsAtCompileTime!=Dynamic) || (cols<=MaxColsAtCompileTime)) && rows>=0 && cols>=0 && "Invalid sizes when resizing a matrix or array."' failed.
Aborted (core dumped)

**Comment by milmillin** [comment]
You need to use our fork of Topy found here: https://github.com/milmillin/topy. It will generate the `.bin` files. Basically, you will need to run `python scripts/optimise.py your-file.tpd output-dir`.

**Comment by Wangmmstar** [comment]
> You need to use our fork of Topy found here: https://github.com/milmillin/topy. It will generate the `.bin` files. Basically, you will need to run `python scripts/optimise.py your-file.tpd output-dir`.

Hi, thanks for your reply. I used the topy from your fork. Firstly, there is a typo in optimise.py, in the main function, it should be optimise(argv[1], argv[2]), otherwise it would throw error. Secondly, I designated the output path like you said, but the output is still 50 vtk files. I couldn't find the .bin file.

**Comment by LouYu2015** [comment]
The .bin file feature was added in https://github.com/milmillin/topy/commit/bdfee6e7a312355215232769d047544d10b1a3f2.

I think this is still a version mismatch. Could you double check if your ToPy code contains save_3d_array?

**Comment by Wangmmstar** [comment]
> 

Hi Yu, Thanks for your timely reply! I double checked the topy I downloaded. The function named save_3d array is mentioned in visualization.py and optimization.py. I. do think this is the correct version. But I am not sure if the __main__ function is correct. As Maybe the save_3d_array function is not called?

**Comment by Wangmmstar** [comment]
> The .bin file feature was added in [milmillin/topy@bdfee6e](https://github.com/milmillin/topy/commit/bdfee6e7a312355215232769d047544d10b1a3f2).
> 
> I think this is still a version mismatch. Could you double check if your ToPy code contains save_3d_array?

Hi Yu, Thanks for your timely reply! I double checked the topy I downloaded. The function named save_3d array is mentioned in visualization.py and optimization.py. I. do think this is the correct version. But I am not sure if the main function is correct. As Maybe the save_3d_array function is not called?

**Comment by LouYu2015** [comment]
What is the value of NUM_ELEM_Z in the input file? Could you try to add some print statements to see which branch is executed in this `if t.nelz:` block? https://github.com/milmillin/topy/blob/master/topy/optimisation.py#L33

**Comment by Wangmmstar** [comment]
> What is the value of NUM_ELEM_Z in the input file? Could you try to add some print statements to see which branch is executed in this `if t.nelz:` block? https://github.com/milmillin/topy/blob/master/topy/optimisation.py#L33

Hi Yu, I added print function for each statement below you mentioned. But it seems none of the function are called as there is no printed  function showed on the terminal.  Plus, NUM_ELEM_Z is 58 in my input file. I attached the input tpd file below.

Below are the lines I modified: 

# Below this line we print info and create images or geometry:
        if t.nelz:
            print("The t.nelz is operated")
            params = {
                'prefix': t.probname,
                'iternum': t.itercount,
                'time': 'none',
                'dir': dir
            }
            if save:
                print("The save in t.nelz is operated")
                create_3d_geom(t.desvars, **params)
                save_3d_array(t.desvars, **params)
        else:
            print("t.nelz didn't meet, run else")
            params = {
                'prefix': t.probname,
                'iternum': t.itercount,
                'time': 'none',
                'filetype': 'png',
                'dir': dir
            }
            if save:
                print("create 2d images but no save")
                create_2d_imag(t.desvars, **params)

Below are the output showed on terminal:

$ python scripts/optimise.py results/test3 results/test
================================================================================
ToPy problem definition (TPD) file successfully parsed.
TPD file name: results/test3 (v2007)
--------------------------------------------------------------------------------
Domain discretisation (NUM_ELEM_X x NUM_ELEM_Y x NUM_ELEM_Z) = 62 x 76 x 58
Element type (ELEM_K) = H8
Filter radius (FILT_RAD) = 1.8
Number of iterations (NUM_ITER) = 50
Problem type (PROB_TYPE) = comp
Problem name (PROB_NAME) = test3
Damping factor (ETA) = 0.40
Passive elements (PASV_ELEM) specified
No active elements (ACTV_ELEM) specified
================================================================================
 Iter | Obj. func.   | Vol.  | Change     | P_FAC | Q_FAC | Ave ETA | S-V frac. 
--------------------------------------------------------------------------------
ToPy: Solution for FEA converged after 514 iterations.
   1  | 1.756511e+02 | 0.040 | 2.0000e-01 | 1.000 | 1.000 |  0.400  |  0.349 
ToPy: Solution for FEA converged after 395 iterations.
   2  | 5.530449e+01 | 0.040 | 2.0000e-01 | 1.000 | 1.000 |  0.400  |  0.353 
ToPy: Solution for FEA converged after 332 iterations.
   3  | 3.204802e+01 | 0.040 | 2.0000e-01 | 1.000 | 1.000 |  0.400  |  0.393 
ToPy: Solution for FEA converged after 320 iterations.
   4  | 2.408602e+01 | 0.040 | 2.0000e-01 | 1.000 | 1.000 |  0.400  |  0.452 
ToPy: Solution for FEA converged after 315 iterations.
   5  | 2.019947e+01 | 0.040 | 2.0000e-01 | 1.000 | 1.000 |  0.400  |  0.504 
ToPy: Solution for FEA converged after 308 iterations.
   6  | 1.825129e+01 | 0.040 | 1.7810e-01 | 1.000 | 1.000 |  0.400  |  0.542 
ToPy: Solution for FEA converged after 287 iterations.
   7  | 1.802941e+01 | 0.040 | 1.2342e-01 | 1.000 | 1.000 |  0.400  |  0.573 
ToPy: Solution for FEA converged after 286 iterations.
   8  | 1.789349e+01 | 0.040 | 9.6038e-02 | 1.000 | 1.000 |  0.400  |  0.599 
ToPy: Solution for FEA converged after 286 iterations.
   9  | 1.780334e+01 | 0.040 | 7.3903e-02 | 1.000 | 1.000 |  0.400  |  0.621 
ToPy: Solution for FEA converged after 287 iterations.
  10  | 1.774053e+01 | 0.040 | 6.3916e-02 | 1.000 | 1.000 |  0.400  |  0.639 
ToPy: Solution for FEA converged after 287 iterations.
  11  | 1.769494e+01 | 0.040 | 5.3607e-02 | 1.000 | 1.000 |  0.400  |  0.655 
ToPy: Solution for FEA converged after 287 iterations.
  12  | 1.766083e+01 | 0.040 | 4.4181e-02 | 1.000 | 1.000 |  0.400  |  0.668 
ToPy: Solution for FEA converged after 287 iterations.
  13  | 1.763473e+01 | 0.040 | 3.6230e-02 | 1.000 | 1.000 |  0.400  |  0.678 
ToPy: Solution for FEA converged after 286 iterations.
  14  | 1.761438e+01 | 0.040 | 2.9703e-02 | 1.000 | 1.000 |  0.400  |  0.688 
ToPy: Solution for FEA converged after 285 iterations.
  15  | 1.759822e+01 | 0.040 | 2.4395e-02 | 1.000 | 1.000 |  0.400  |  0.696 
ToPy: Solution for FEA converged after 284 iterations.
  16  | 1.758514e+01 | 0.040 | 7.6474e-02 | 1.200 | 1.050 |  0.400  |  0.719 
ToPy: Solution for FEA converged after 341 iterations.
  17  | 1.940848e+01 | 0.040 | 1.5585e-01 | 1.400 | 1.100 |  0.400  |  0.762 
ToPy: Solution for FEA converged after 356 iterations.
  18  | 2.107970e+01 | 0.040 | 2.0000e-01 | 1.600 | 1.150 |  0.400  |  0.811 
ToPy: Solution for FEA converged after 375 iterations.
  19  | 2.211863e+01 | 0.040 | 2.0000e-01 | 1.800 | 1.200 |  0.400  |  0.854 
ToPy: Solution for FEA converged after 410 iterations.
  20  | 2.222418e+01 | 0.040 | 2.0000e-01 | 2.000 | 1.250 |  0.400  |  0.891 
ToPy: Solution for FEA converged after 437 iterations.
  21  | 2.158107e+01 | 0.040 | 2.0000e-01 | 2.200 | 1.300 |  0.400  |  0.922 
ToPy: Solution for FEA converged after 460 iterations.
  22  | 2.068870e+01 | 0.040 | 2.0000e-01 | 2.400 | 1.350 |  0.400  |  0.946 
ToPy: Solution for FEA converged after 471 iterations.
  23  | 1.996181e+01 | 0.040 | 2.0000e-01 | 2.600 | 1.400 |  0.400  |  0.961 
ToPy: Solution for FEA converged after 479 iterations.
  24  | 1.951937e+01 | 0.040 | 2.0000e-01 | 2.800 | 1.450 |  0.400  |  0.970 
ToPy: Solution for FEA converged after 456 iterations.
  25  | 1.925285e+01 | 0.040 | 2.0000e-01 | 2.800 | 1.500 |  0.400  |  0.976 
ToPy: Solution for FEA converged after 454 iterations.
  26  | 1.904490e+01 | 0.040 | 2.0000e-01 | 2.800 | 1.550 |  0.400  |  0.979 
ToPy: Solution for FEA converged after 440 iterations.
  27  | 1.891056e+01 | 0.040 | 2.0000e-01 | 2.800 | 1.600 |  0.400  |  0.982 
ToPy: Solution for FEA converged after 440 iterations.
  28  | 1.881102e+01 | 0.040 | 2.0000e-01 | 2.800 | 1.650 |  0.400  |  0.984 
ToPy: Solution for FEA converged after 437 iterations.
  29  | 1.873183e+01 | 0.040 | 2.0000e-01 | 2.800 | 1.700 |  0.400  |  0.986 
ToPy: Solution for FEA converged after 431 iterations.
  30  | 1.866949e+01 | 0.040 | 2.0000e-01 | 2.800 | 1.750 |  0.400  |  0.988 
ToPy: Solution for FEA converged after 430 iterations.
  31  | 1.861794e+01 | 0.040 | 2.0000e-01 | 2.800 | 1.800 |  0.400  |  0.990 
ToPy: Solution for FEA converged after 430 iterations.
  32  | 1.857450e+01 | 0.040 | 2.0000e-01 | 2.800 | 1.850 |  0.400  |  0.991 
ToPy: Solution for FEA converged after 429 iterations.
  33  | 1.853542e+01 | 0.040 | 2.0000e-01 | 2.800 | 1.900 |  0.400  |  0.993 
ToPy: Solution for FEA converged after 412 iterations.
  34  | 1.850213e+01 | 0.040 | 2.0000e-01 | 2.800 | 1.950 |  0.400  |  0.994 
ToPy: Solution for FEA converged after 426 iterations.
  35  | 1.847542e+01 | 0.040 | 2.0000e-01 | 2.800 | 2.000 |  0.400  |  0.995 
ToPy: Solution for FEA converged after 419 iterations.
  36  | 1.845538e+01 | 0.040 | 2.0000e-01 | 2.800 | 2.050 |  0.400  |  0.996 
ToPy: Solution for FEA converged after 412 iterations.
  37  | 1.843864e+01 | 0.040 | 2.0000e-01 | 2.800 | 2.100 |  0.400  |  0.997 
ToPy: Solution for FEA converged after 405 iterations.
  38  | 1.842576e+01 | 0.040 | 2.0000e-01 | 2.800 | 2.150 |  0.400  |  0.998 
ToPy: Solution for FEA converged after 417 iterations.
  39  | 1.841440e+01 | 0.040 | 2.0000e-01 | 2.800 | 2.200 |  0.400  |  0.998 
ToPy: Solution for FEA converged after 404 iterations.
  40  | 1.840486e+01 | 0.040 | 2.0000e-01 | 2.800 | 2.250 |  0.400  |  0.999 
ToPy: Solution for FEA converged after 408 iterations.
  41  | 1.839767e+01 | 0.040 | 2.0000e-01 | 2.800 | 2.300 |  0.400  |  0.999 
ToPy: Solution for FEA converged after 406 iterations.
  42  | 1.839248e+01 | 0.040 | 2.0000e-01 | 2.800 | 2.350 |  0.400  |  0.999 
ToPy: Solution for FEA converged after 406 iterations.
  43  | 1.838917e+01 | 0.040 | 2.0000e-01 | 2.800 | 2.400 |  0.400  |  1.000 
ToPy: Solution for FEA converged after 392 iterations.
  44  | 1.838659e+01 | 0.040 | 2.0000e-01 | 2.800 | 2.450 |  0.400  |  1.000 
ToPy: Solution for FEA converged after 396 iterations.
  45  | 1.838467e+01 | 0.040 | 2.0000e-01 | 2.800 | 2.500 |  0.400  |  1.000 
ToPy: Solution for FEA converged after 397 iterations.
  46  | 1.838293e+01 | 0.040 | 2.0000e-01 | 2.800 | 2.550 |  0.400  |  1.000 
ToPy: Solution for FEA converged after 381 iterations.
  47  | 1.838176e+01 | 0.040 | 1.7629e-01 | 2.800 | 2.600 |  0.400  |  1.000 
ToPy: Solution for FEA converged after 389 iterations.
  48  | 1.838097e+01 | 0.040 | 1.7865e-01 | 2.800 | 2.650 |  0.400  |  1.000 
ToPy: Solution for FEA converged after 384 iterations.
  49  | 1.838059e+01 | 0.040 | 1.5515e-01 | 2.800 | 2.700 |  0.400  |  1.000 
ToPy: Solution for FEA converged after 381 iterations.
  50  | 1.838022e+01 | 0.040 | 1.8025e-01 | 2.800 | 2.750 |  0.400  |  1.000 

Solid plus void to total elements fraction = 0.99997
50 iterations took 45.897 minutes (55.077 seconds/iteration)
[test3.zip](https://github.com/milmillin/passive-gripper/files/11141069/test3.zip)

**Comment by Wangmmstar** [comment]
> What is the value of NUM_ELEM_Z in the input file? Could you try to add some print statements to see which branch is executed in this `if t.nelz:` block? https://github.com/milmillin/topy/blob/master/topy/optimisation.py#L33

I tried some other print/logger function in other different locations. But one of them are output. I am not sure these functions call each other. I've attached the whole optimisation.py in my topy folder.
[optimisation.zip](https://github.com/milmillin/passive-gripper/files/11154199/optimisation.zip)
